version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nodejs:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  vuejs:
    build: ./new-vue-project
    ports:
      - "8080:8080"
    command: npm run serve

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - nodejs
      - vuejs
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  mongo-data: