services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server
      - mongodb
    networks:
      - koto-net

  client:
    build: ./client
    container_name: vue-client
    ports:
      - "8080:8080"
    networks:
      - koto-net

  server:
    build: ./server
    container_name: node-server
    ports:
      - "5001:5000"
    networks:
      - koto-net
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Указываем том для постоянного хранения данных
    networks:
      - koto-net

networks:
  koto-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local  # Определяем постоянный том для хранения данных MongoDB